
#ifndef _GLIP_H_
#define _GLIP_H_

#include "glip_common.h"
#include "glip_adjrel.h"
#include "glip_gpqueue_by_Falcao.h"
#include "glip_morphology.h"
#include "glip_arraylist.h"
#include "glip_heap.h"
#include "glip_heap32.h"
#include "glip_heap64f.h"
#include "glip_heap_lex.h"
#include "glip_heap32fi_lex.h"
#include "glip_heappair.h"
#include "glip_ift.h"
#include "glip_image64.h"
#include "glip_image8.h"
#include "glip_string.h"
#include "glip_cimage.h"
#include "glip_cimage32f.h"
#include "glip_filelist.h"
#include "glip_queue.h"
#include "glip_color.h"
#include "glip_highlight.h"
#include "glip_image32.h"
#include "glip_image32f.h"
#include "glip_imagegraph.h"
#include "glip_graph.h"
#include "glip_layeredgraph.h"
#include "glip_filtering.h"
#include "glip_superpixels.h"
#include "glip_evaluation.h"
#include "glip_radiometric.h"
#include "glip_analysis.h"
#include "glip_marker.h"
#include "glip_features.h"
#include "glip_graphclustering.h"
#include "glip_attributelist.h"
#include "glip_configfile.h"
#include "glip_geometry.h"
#include "glip_ctree.h"
#include "glip_llw.h"
#include "glip_draw.h"
#include "glip_band.h"

#include "glip_scene.h"
#include "glip_scene32.h"
#include "glip_scene32f.h"
#include "glip_scene64f.h"
#include "glip_scene16.h"
#include "glip_scene8.h"
#include "glip_adjrel3.h"
#include "glip_scnmath.h"
#include "glip_matrix.h"
#include "glip_bmap.h"
#include "glip_set.h"
#include "glip_stack.h"
#include "glip_pqueue32.h"
#include "glip_pqueue16.h"
#include "glip_pqueue8.h"
#include "glip_hashtable.h"
#include "glip_curve.h"
#include "glip_radiometric3.h"
#include "glip_filtering3.h"
#include "glip_segmentation3.h"
#include "glip_morphology3.h"
#include "glip_analysis3.h"
#include "glip_marker3.h"
#include "glip_gradient3.h"


#endif

